[package]
name = "substratee_client"
version = "2.0.0"
authors = ["Supercomputing Systems AG <info@scs.ch>"]
edition = "2018"

[dependencies]
ws = "0.7"
hex = "0.3"
log = "0.4"
rand = "0.6"
clap = { version = "2.33", features = [ "yaml" ] }
env_logger = "0.6"
schnorrkel = "0.1"
serde = "1.0"
serde_json = "1.0"
tiny-bip39 = "0.6.0"
blake2-rfc = { version = "0.2.18", default-features = false}
hex-literal = "0.2.0"
serde_derive = "1.0"
parity-codec = { version = "3.0", default-features = false }
primitive-types = { version = "0.2", default-features = false, features = ["codec"] }

substrate_bip39 = { package="substrate-bip39", git = "https://github.com/paritytech/substrate-bip39" }

sgx_types = { git = "https://github.com/baidu/rust-sgx-sdk" }

[dependencies.my_node_runtime]
git = "https://github.com/scs/substraTEE-node"
branch = "update_substrate"
package = "substratee-node-runtime"
features = ["no_global_allocator"]

[dependencies.substrate-api-client]
git = "https://github.com/scs/substrate-api-client"
branch = "update_substrate"
default-features = false

[dependencies.system]
git = "https://github.com/paritytech/substrate"
rev = '56b0273fd48b4e742e9da7317bc8e132a740b684'
package = "srml-system"

[dependencies.primitives]
git = "https://github.com/paritytech/substrate"
rev = '56b0273fd48b4e742e9da7317bc8e132a740b684'
package = "substrate-primitives"

[dependencies.node-primitives]
git = "https://github.com/paritytech/substrate"
rev = '56b0273fd48b4e742e9da7317bc8e132a740b684'

[dependencies.substrate-keyring]
git = "https://github.com/paritytech/substrate"
rev = '56b0273fd48b4e742e9da7317bc8e132a740b684'

[dependencies.runtime_primitives]
git = "https://github.com/paritytech/substrate"
rev = '56b0273fd48b4e742e9da7317bc8e132a740b684'
package = "sr-primitives"
default-features = false

[dependencies.sgx_crypto_helper]
git = "https://github.com/baidu/rust-sgx-sdk"
default-features = false
