[workspace]
members = [
	 "worker",
	 "worker/worker-api",
	 "substratee-node-calls",
	 "client",
	 "stf",
]

[patch.crates-io]
ed25519-dalek = { git = "https://github.com/scs/ed25519-dalek.git", branch = "no_std_sgx" }
