[workspace]

members = [
	 "worker",
	 "worker/worker-api",
	 "substratee-node-calls",
	 "client",
	 "stf",
	 "application-crypto"
]

[patch.'https://github.com/paritytech/substrate']
sr-io = { git = "https://github.com/scs/substraTEE-node", rev = 'd4a057c5841796994b46b6b35de922ec5777fec5' }
primitives = { git = "https://github.com/scs/substrate-api-client", package = 'substrate-primitives', rev = 'a1e82a08418dc5de0b6bd3bf016bcee004736441' }
substrate-application-crypto = { path = "application-crypto"}

[patch.crates-io]
ed25519-dalek = { git = "https://github.com/scs/ed25519-dalek.git", branch = "no_std_sgx" }
