[workspace]

members = [
	 "worker",
	 "worker/worker-api",
	 "substratee-node-calls",
	 "client",
	 "stf",
	 "application-crypto"
]

[patch.'https://github.com/paritytech/substrate']
sr-io = { git = "https://github.com/scs/substraTEE-node", tag = "M5", default-features=false }
substrate-executor = { git = "https://github.com/scs/substraTEE-node", tag = "M5", default-features=false }
substrate-primitives = { git = "https://github.com/scs/substrate-api-client", tag = "api-M1.3"}
substrate-application-crypto = { path = "application-crypto"}

[patch.crates-io]
ed25519-dalek = { git = "https://github.com/scs/ed25519-dalek.git", branch = "no_std_sgx"}