[workspace]

members = [
	 "worker",
	 "worker/worker-api",
	 "substratee-node-calls",
	 "client",
	 "stf",
]

# cargo bug https://github.com/rust-lang/cargo/issues/5478
# forces us to add extra characters to github url, like introducing double slashes
[patch.'https://github.com/scs/substrate']
primitives = { git = "https://github.com/scs//substrate", package = 'substrate-primitives', tag = "substraTEE-M5.1" }
substrate-application-crypto = { git = "https://github.com/scs//substrate", tag = "substraTEE-M5.1" }

[patch.crates-io]
ed25519-dalek = { git = "https://github.com/scs/ed25519-dalek.git", branch = "no_std_sgx" }
