[workspace]

members = [
	"worker",
	"client",
	"enclave",
	"enclave/wasm"
]

[patch.crates-io]
ring 			= { git = "https://github.com/mesalock-linux/ring-sgx" }
untrusted 		= { git = "https://github.com/briansmith/untrusted", tag = "ring-master" }
serde           = { git = "https://github.com/mesalock-linux/serde-sgx", default-features = false, features = ["mesalock_sgx"] }
serde_derive 	= { git = "https://github.com/mesalock-linux/serde-sgx", default-features = false, features = ["mesalock_sgx"] }
serde_json 		= { git = "https://github.com/mesalock-linux/serde-json-sgx", default-features = false, features = ["mesalock_sgx"] }

 [patch.'https://github.com/mesalock-linux/itoa-sgx.git']
itoa = { git = "https://github.com/mesalock-linux/itoa-sgx", default-features = false, features = ["mesalock_sgx"] }

# [patch.'https://github.com/mesalock-linux/ring-sgx']
# ring = { git ="https://github.com/scs/ring-sgx" }
