[workspace]

members = [
	 "worker",
	 "worker/worker-api",
	 "substratee-node-calls",
	 "client",
]

[patch.'https://github.com/paritytech/substrate']
sr-io = { git = "https://github.com/scs/substraTEE-node", tag = "M4" }
substrate-executor = { git = "https://github.com/scs/substraTEE-node", tag = "M4" }
