[workspace]

members = [
	 "worker",
	 "worker/worker-api",
	 "substratee-node-calls",
	 "client",
]

[patch.'https://github.com/paritytech/substrate']
sr-io = { git = "https://github.com/scs/substraTEE-node", branch = "cl-host-optional", default-features=false }
substrate-executor = { git = "https://github.com/scs/substraTEE-node", branch = "cl-host-optional", default-features=false }

#[patch.crates-io]
#rustls = { git = "https://github.com/mesalock-linux/rustls", rev="36995713775439e1a60a01cfa327e045a61020a6"}