[package]
name = "simplyr"
authors = ["BEST project developers"]
description = "Implementation of matching algorithms for digital energy markets."
homepage = "https://github.com/BESTenergytrade/simplyR"
license = "MIT"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.29", features = ["derive", "cargo"] }
serde = { version = "1.0.147", features=['derive'] }
serde_json = "1.0.87"
simplyr-lib = { path = "simplyr-lib" }