[package]
name = "srml-balances"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", optional = true }
safe-mix = { version = "1.0", default-features = false}
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }

sgx_tstd      = { rev = "v1.1.0", git = "https://github.com/apache/teaclave-sgx-sdk.git", features = ["untrusted_fs","net","backtrace"]}
sgx_types     = { rev = "v1.1.0", git = "https://github.com/apache/teaclave-sgx-sdk.git"}
sgx_log       = { package = "log", tag = "sgx_1.1.0" , git = "https://github.com/mesalock-linux/log-sgx"}

[dependencies.rstd]
git = 'https://github.com/scs/substrate'
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"
package = "sr-std"
features = ["disable_allocator"]
default-features = false

[dependencies.sr-primitives]
git = 'https://github.com/scs/substrate'
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"
package = "sr-primitives"
default-features = false

[dependencies.support]
default-features = false
git = "https://github.com/scs/substrate"
package = "srml-support"
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"

[dependencies.system]
default-features = false
git = "https://github.com/scs/substrate"
package = "srml-system"
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"

[dev-dependencies]
#runtime-io ={ package = "sr-io", path = "../../core/sr-io", default-features = false }
#primitives = { package = "substrate-primitives",  path = "../../core/primitives" }

[features]
default = ["std"]
std = [
	"serde",
	"safe-mix/std",
	"codec/std",
	"rstd/std",
	"support/std",
	"sr-primitives/std",
	"system/std",
]
