[package]
name = "substratee-stf"
version = "0.1.0"
authors = ["Supercomputing Systems AG <info@scs.ch>"]
edition = "2018"

[features]
default = []
sgx = [
    "sgx_tstd",
    "env_logger",
    "log",
    "sr-io/sgx",
    ]

[dependencies]
log               = { version = "0.4.7", git = "https://github.com/mesalock-linux/log-sgx", optional=true }
env_logger        = { version = "0.6.2", git = "https://github.com/mesalock-linux/env_logger-sgx", optional=true }

[dependencies.sgx_tstd]
rev = "v1.0.9"
git = "https://github.com/baidu/rust-sgx-sdk"
features = ["untrusted_fs","net","backtrace"]
optional = true

[dependencies.codec]
package = "parity-scale-codec"
version = "1.0.0"
default-features = false
features = ["derive"]

[dependencies.primitives]
git = "https://github.com/scs/substrate"
package = "substrate-primitives"
default-features = false

[dependencies.runtime_primitives]
git = 'https://github.com/scs/substrate'
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"
package = "sr-primitives"
default-features = false

[dependencies.balances]
default-features = false
git = "https://github.com/scs/substrate"
package = "srml-balances"
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"

[dependencies.timestamp]
default-features = false
git = "https://github.com/scs/substrate"
package = "srml-timestamp"
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"

[dependencies.system]
default-features = false
git = "https://github.com/scs/substrate"
package = "srml-system"
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"

[dependencies.srml-support]
default-features = false
git = "https://github.com/scs/substrate"
package = "srml-support"
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"

[dependencies.indices]
default-features = false
git = "https://github.com/scs/substrate"
package = "srml-indices"
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"

[dependencies.version]
default-features = false
git = "https://github.com/scs/substrate"
package = "sr-version"
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"

[dependencies.sr-io]
git = "https://github.com/scs/substraTEE-node"
package = 'sr-io'
rev = "acd97f49be1f691c35f567dd79f7391ce9554a9f"
default-features=false
features = ["no_oom", "no_panic_handler", "debug"]




