[package]
name = "substratee-stf"
version = "0.1.0"
authors = ["Supercomputing Systems AG <info@scs.ch>"]
edition = "2018"

[features]
default = []
sgx = [
    "sgx_tstd",
    "env_logger",
    "log",
    "sr-io",
]

[dependencies]
log               = { version = "0.4", git = "https://github.com/mesalock-linux/log-sgx", optional = true }
env_logger        = { version = "0.7", git = "https://github.com/mesalock-linux/env_logger-sgx", optional = true }

[dependencies.sgx_tstd]
git = "https://github.com/baidu/rust-sgx-sdk.git"
features = ["untrusted_fs","net","backtrace"]
rev = "v1.1.0"
optional = true

[dependencies.codec]
default-features = false
package = "parity-scale-codec"
version = "1.0.0"
features = ["derive"]

[dependencies.primitives]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "substrate-primitives"
rev = "3bf9540e72df5ecb3955845764dfee7dcdbb26b5"
features = ["full_crypto"]

[dependencies.application-crypto]
default-features = false
git = "https://github.com/paritytech/substrate"
rev = "3bf9540e72df5ecb3955845764dfee7dcdbb26b5"
package = "substrate-application-crypto"
features = ["full_crypto"]

[dependencies.runtime_primitives]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "sr-primitives"
rev = "3bf9540e72df5ecb3955845764dfee7dcdbb26b5"

[dependencies.balances]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "pallet-balances"
rev = "3bf9540e72df5ecb3955845764dfee7dcdbb26b5"

# timestamp pulls in blake2-rfc with std
#[dependencies.timestamp]
#default-features = false
#git = "https://github.com/paritytech/substrate"
#package = "pallet-timestamp"
#rev = "3bf9540e72df5ecb3955845764dfee7dcdbb26b5"

[dependencies.system]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "palette-system"
rev = "3bf9540e72df5ecb3955845764dfee7dcdbb26b5"

[dependencies.support]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "palette-support"
rev = "3bf9540e72df5ecb3955845764dfee7dcdbb26b5"

[dependencies.indices]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "pallet-indices"
rev = "3bf9540e72df5ecb3955845764dfee7dcdbb26b5"

[dependencies.version]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "sr-version"
rev = "3bf9540e72df5ecb3955845764dfee7dcdbb26b5"

[dependencies.sr-io]
default-features = false
optional = true
path = "../substrate-sgx/sr-io"
package = "sr-io"
features = ["disable_oom", "disable_panic_handler", "disable_allocator", "sgx"]
