[package]
name = "srml-balances"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", optional = true }
safe-mix = { version = "1.0", default-features = false}
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }

[dependencies.rstd]
git = 'https://github.com/paritytech/substrate'
rev = "9b08e7ff938a45dbec7fcdb854063202e2b0cb48"
package = "sr-std"
features = ["no_global_allocator"]
default-features = false

[dependencies.sr_primitives]
git = 'https://github.com/paritytech/substrate'
rev = "9b08e7ff938a45dbec7fcdb854063202e2b0cb48"
package = "sr-primitives"
default-features = false

[dependencies.support]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "srml-support"
rev = "9b08e7ff938a45dbec7fcdb854063202e2b0cb48"

[dependencies.system]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "srml-system"
rev = "9b08e7ff938a45dbec7fcdb854063202e2b0cb48"

[dev-dependencies]
#runtime-io ={ package = "sr-io", path = "../../core/sr-io", default-features = false }
#primitives = { package = "substrate-primitives",  path = "../../core/primitives" }

[features]
default = ["std"]
std = [
	"serde",
	"safe-mix/std",
	"codec/std",
	"rstd/std",
	"support/std",
	"sr-primitives/std",
	"system/std",
]
