[package]
name = "sgx-externalities"
version = "0.1.0"
authors = ["Supercomputing Systems AG <info@scs.ch>"]
edition = "2018"

[dependencies]
environmental = { version = "1.0.1", default-features = false}
sgx_tstd      = { rev = "v1.1.0", git = "https://github.com/baidu/rust-sgx-sdk", features = ["untrusted_fs","net","backtrace"]}
sgx_types     = { rev = "v1.1.0", git = "https://github.com/baidu/rust-sgx-sdk"}
sgx_log       = { package = "log",  version = "0.4", git = "https://github.com/mesalock-linux/log-sgx"}
