[package]
name = "substratee-node-calls"
version = "4.0.0"
authors = ["clangenbacher <christian.langenbacher@scs.ch>"]
edition = "2018"

[dependencies]
log = "0.4"
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
primitive-types = { version = "0.5.0", default-features = false, features = ["codec"] }
regex = "1"

[dependencies.substrate-api-client]
git = "https://github.com/scs/substrate-api-client"
default-features = false

[dependencies.my_node_runtime]
git = "https://github.com/scs/substraTEE-node"
branch = "cl-host-optional"
package = "substratee-node-runtime"
features = ["no_global_allocator"]

[dependencies.primitives]
git = "https://github.com/paritytech/substrate"
rev = "9b08e7ff938a45dbec7fcdb854063202e2b0cb48"
package = "substrate-primitives"

[dependencies.srml-support]
git = "https://github.com/paritytech/substrate"
rev = "9b08e7ff938a45dbec7fcdb854063202e2b0cb48"