[package]
name = "sgx_crypto_helper"
version = "1.0.0"
authors = ["Baidu"]
repository = "https://github.com/baidu/rust-sgx-sdk"
license-file = "LICENSE"
documentation = "https://dingelish.github.io/"
description = "Rust SGX SDK provides the ability to write Intel SGX applications in Rust Programming Language."

[lib]
name = "sgx_crypto_helper"
crate-type = ["staticlib","rlib"]

[features]
default = []
enclave_cargo = []

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_tcrypto = { git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_tstd = { git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_types = { git = "https://github.com/baidu/rust-sgx-sdk" }

[dependencies]
serde = { git = "https://github.com/baidu/rust-sgx-sdk" }
serde_derive = { git = "https://github.com/baidu/rust-sgx-sdk" }
serde-big-array = { git = "https://github.com/baidu/rust-sgx-sdk" }
itertools = { version = "*", default-features = false }
