[package]
name = "substratee_worker_enclave"
version = "4.0.0"
authors = ["Supercomputing Systems AG <info@scs.ch>"]

[workspace]
members = ["wasm"]

[lib]
name = "substratee_worker_enclave"
crate-type = ["staticlib"]

[features]
default = []

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_tse       = { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_tstd      = { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk", features = ["untrusted_fs","net","backtrace"] }
sgx_rand      = { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_trts      = { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_types     = { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_tseal     = { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_tcrypto   = { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_serialize = { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_tunittest = { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk" }

[dependencies]
aes               = { version = "0.3.2" }
ofb               = { version = "0.1.1" }
codec             = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
primitive-types   = { version = "0.5.0", default-features = false, features = ["codec"] }
sgx-crypto-helper = { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk", package = "sgx_tcrypto_helper" }
log               = { version = "0.4.7", git = "https://github.com/mesalock-linux/log-sgx" }
env_logger        = { version = "0.6.2", git = "https://github.com/mesalock-linux/env_logger-sgx" }
#rust-crypto       = { rev = "c379c41663889758d7a851f8a7bd3eb26f271827", git = "https://github.com/mesalock-linux/rust-crypto-sgx" }

# for wasm code
wasmi           = { version = "0.5.0", git = "https://github.com/mesalock-linux/wasmi-sgx" }
serde        	= { version = "1.0.97", git = "https://github.com/mesalock-linux/serde-sgx" }
serde_json      = { version = "1.0.36", git = "https://github.com/mesalock-linux/serde-json-sgx"}
sgxwasm         = { path = "sgxwasm" }
lazy_static     = { version = "1.1.0", features = ["spin_no_std"] }

# for attestation
chrono          = { version = "0.4.7",  git = "https://github.com/mesalock-linux/chrono-sgx" }
base64          = { version = "0.10.1", git = "https://github.com/mesalock-linux/rust-base64-sgx" }
num-bigint      = { version = "0.2.2",  git = "https://github.com/mesalock-linux/num-bigint-sgx" }
serde_derive    = { version = "1.0.97", git = "https://github.com/mesalock-linux/serde-sgx" }
httparse        = { version = "1.3.2",  default-features = false }
itertools       = { version = "0.7.8",  default-features = false, features = []}
bit-vec         = { version = "0.6",    default-features = false }
rust-base58     = { rev = "3fe87eafe81d1ff5e6cf2fb63c6976fc4e06ac44", git = "https://github.com/mesalock-linux/rust-base58-sgx", default-features = false, features=["mesalock_sgx"] }

[dependencies.webpki]
git              = "https://github.com/mesalock-linux/webpki"
branch           = "mesalock_sgx"
version          = "0.21.0"

[dependencies.webpki-roots]
git              = "https://github.com/mesalock-linux/webpki-roots"
branch           = "mesalock_sgx"
version          = "0.17.0"

# use renamed blake2-rfc
[dependencies.blake2-no-std]
git     = "https://github.com/cesarb/blake2-rfc"
package = "blake2-rfc"
version = "0.2.18"
default-features = false

[dependencies.yasna]
git      = "https://github.com/mesalock-linux/yasna.rs-sgx"
rev      = "29f0707027ce3b06ddb7daf4086ef673dbcb14ff"
# rev      = "d4619dfa4a5ff73b8bf6e8c3bd4e977fc1634a19" # fixing to this revision to have buf public
default-features = false
features = ["bit-vec", "num-bigint", "chrono", "mesalock_sgx"]

[dependencies.rustls]
git      = "https://github.com/mesalock-linux/rustls"
rev      = "36995713775439e1a60a01cfa327e045a61020a6"
features = ["dangerous_configuration"]

[dependencies.sr-io]
git = "https://github.com/scs/substraTEE-node"
package = 'sr-io'
branch = "brenzi-private-tx"
default-features=false
features = ["no_oom", "no_panic_handler", "sgx"]

[dependencies.sgx_serialize_derive]
git = "https://github.com/baidu/rust-sgx-sdk"
rev = "v1.0.9"

[dependencies.primitives]
git = "https://github.com/scs/substrate-api-client"
package = "substrate-primitives"
branch = "no_std_rstd"
default-features = false

[dependencies.runtime_primitives]
git = 'https://github.com/paritytech/substrate'
rev = "9b08e7ff938a45dbec7fcdb854063202e2b0cb48"
package = "sr-primitives"
default-features = false

[dependencies.rstd]
git = 'https://github.com/paritytech/substrate'
rev = "9b08e7ff938a45dbec7fcdb854063202e2b0cb48"
package = "sr-std"
features = ["no_global_allocator"]
default-features = false

[dependencies.substrate-api-client]
git = "https://github.com/scs/substrate-api-client"
branch = "no_std_rstd"
default-features = false

# runtime stuff
[dependencies.balances]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "srml-balances"
rev = "9b08e7ff938a45dbec7fcdb854063202e2b0cb48"

[dependencies.timestamp]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "srml-timestamp"
rev = "9b08e7ff938a45dbec7fcdb854063202e2b0cb48"

[dependencies.system]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "srml-system"
rev = "9b08e7ff938a45dbec7fcdb854063202e2b0cb48"

[dependencies.srml-support]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "srml-support"
rev = "9b08e7ff938a45dbec7fcdb854063202e2b0cb48"

[dependencies.indices]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "srml-indices"
rev = "9b08e7ff938a45dbec7fcdb854063202e2b0cb48"

[dependencies.version]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "sr-version"
rev = "9b08e7ff938a45dbec7fcdb854063202e2b0cb48"

#[dependencies.node_runtime]
#default-features = false
#git = "https://github.com/paritytech/substrate"
#package = "node-runtime"
#rev = "9b08e7ff938a45dbec7fcdb854063202e2b0cb48"

[patch.'https://github.com/paritytech/substrate']
sr-io = { git = "https://github.com/scs/substraTEE-node", branch = "brenzi-private-tx"}
substrate-primitives = { git = "https://github.com/scs/substrate-api-client", branch = "no_std_rstd"}
substrate-application-crypto = { path = "../application-crypto"}

[patch.crates-io]
ed25519-dalek = { git = "https://github.com/scs/ed25519-dalek.git", branch = "no_std_sgx"}
