[package]
name = "substratee_worker_enclave"
version = "2.0.0"
authors = ["Supercomputing Systems AG <info@scs.ch>"]

[lib]
name = "substratee_worker_enclave"
crate-type = ["staticlib"]

[features]
default = []

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_tse       = { rev = "v1.0.8", git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_tstd      = { rev = "v1.0.8", git = "https://github.com/baidu/rust-sgx-sdk", features = ["net","backtrace"] }
sgx_rand      = { rev = "v1.0.8", git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_trts      = { rev = "v1.0.8", git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_types     = { rev = "v1.0.8", git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_tseal     = { rev = "v1.0.8", git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_tcrypto   = { rev = "v1.0.8", git = "https://github.com/baidu/rust-sgx-sdk" }
rust-crypto   = { rev = "v1.0.8", git = "https://github.com/baidu/rust-sgx-sdk" }
rust-base58   = { rev = "v1.0.8", git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_serialize = { rev = "v1.0.8", git = "https://github.com/baidu/rust-sgx-sdk" }

[dependencies]
log = { git = "https://github.com/baidu/rust-sgx-sdk" }
blake2-rfc = { version = "0.2.18", default-features = false}
parity-codec = { version = "3.3", default-features = false }
primitive-types = { version = "0.2", default-features = false, features = ["codec"] }
sgx_crypto_helper = { package="sgx_tcrypto_helper", git = "https://github.com/baidu/rust-sgx-sdk" }

# for wasm code
wasmi           = { git = "https://github.com/mesalock-linux/wasmi-sgx" }
serde           = { git = "https://github.com/mesalock-linux/serde-sgx" }
serde_json      = { git = "https://github.com/mesalock-linux/serde-json-sgx"}
sgxwasm         = { path = "sgxwasm" }
lazy_static     = { version = "1.1.0", features = ["spin_no_std"] }

# for attestation
chrono          = { git = "https://github.com/mesalock-linux/chrono-sgx" }
webpki          = { git = "https://github.com/mesalock-linux/webpki", branch = "mesalock_sgx", default-features = false, features = ["mesalock_sgx"]  }
base64          = { git = "https://github.com/mesalock-linux/rust-base64-sgx" }
yasna           = { git = "https://github.com/mesalock-linux/yasna.rs-sgx", features = ["bit-vec", "num-bigint", "chrono"] }
num-bigint      = { git = "https://github.com/mesalock-linux/num-bigint-sgx" }
webpki-roots    = { git = "https://github.com/mesalock-linux/webpki-roots.git", branch = "mesalock_sgx" }
serde_derive    = { git = "https://github.com/mesalock-linux/serde-sgx" }
httparse        = { version = "1.3.2", default-features=false }
itertools       = { version = "0.7.8", default-features = false, features = []}
bit-vec         = { version = "0.6", default-features = false }

# untrusted       = "0.6.2"
untrusted 		= { git = "https://github.com/briansmith/untrusted", tag = "ring-master" }

[dependencies.rustls]
git      = "https://github.com/mesalock-linux/rustls"
branch   = "mesalock_sgx"
features = ["dangerous_configuration"]

# to get features in
# ring = { git ="https://github.com/scs/ring-sgx", features = ["mesalock_sgx"] }

[dependencies.my_node_runtime]
git = "https://github.com/scs/substraTEE-node"
branch = "substratee_registry_module"
package = "substratee-node-runtime"
default-features = false
features = ["no_global_allocator"]

[dependencies.sgx_serialize_derive]
git = "https://github.com/baidu/rust-sgx-sdk"
rev = "v1.0.8"

# !!!!!! no_std trouble https://github.com/w3f/schnorrkel/issues/31
# [dependencies.schnorrkel]
# git = "https://github.com/scs/schnorrkel"
# default-features = false
# features=["alloc", "u64_backend"]

[dependencies.primitives]
git = 'https://github.com/paritytech/substrate'
rev = "56b0273fd48b4e742e9da7317bc8e132a740b684"
package = "substrate-primitives"
default-features = false

#only listed to get no_global_allocator feature in
[dependencies.rstd]
git = 'https://github.com/paritytech/substrate'
rev = "56b0273fd48b4e742e9da7317bc8e132a740b684"
package = "sr-std"
default-features = false
features = ["no_global_allocator"]

#only listed to get no_panic_handler and no_oom features in
[dependencies.runtime_io]
git = 'https://github.com/paritytech/substrate'
rev = "56b0273fd48b4e742e9da7317bc8e132a740b684"
package = "sr-io"
default-features = false
features = ["no_panic_handler", "no_oom"]

[dependencies.runtime_primitives]
git = 'https://github.com/paritytech/substrate'
rev = "56b0273fd48b4e742e9da7317bc8e132a740b684"
package = "sr-primitives"
default-features = false
