[package]
name = "substratee_worker_enclave"
version = "4.0.0"
authors = ["Supercomputing Systems AG <info@scs.ch>"]

[workspace]
members = ["wasm"]

[lib]
name = "substratee_worker_enclave"
crate-type = ["staticlib"]

[features]
default = []

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_tse       = { rev = "v1.0.8", git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_tstd      = { rev = "v1.0.8", git = "https://github.com/baidu/rust-sgx-sdk", features = ["untrusted_fs","net","backtrace"] }
sgx_rand      = { rev = "v1.0.8", git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_trts      = { rev = "v1.0.8", git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_types     = { rev = "v1.0.8", git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_tseal     = { rev = "v1.0.8", git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_tcrypto   = { rev = "v1.0.8", git = "https://github.com/baidu/rust-sgx-sdk" }
rust-crypto   = { rev = "v1.0.8", git = "https://github.com/baidu/rust-sgx-sdk" }
rust-base58   = { rev = "v1.0.8", git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_serialize = { rev = "v1.0.8", git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_tunittest = { rev = "v1.0.8", git = "https://github.com/baidu/rust-sgx-sdk" }

[dependencies]
aes               = { version = "0.3.2" }
ofb               = { version = "0.1.1" }
parity-codec      = { version = "3.0", default-features = false }
primitive-types   = { version = "0.2", default-features = false, features = ["codec"] }
sgx_crypto_helper = { git = "https://github.com/mesalock-linux/sgx_tcrypto_helper", package = "sgx_tcrypto_helper" }
log               = { git = "https://github.com/mesalock-linux/log-sgx" }
env_logger        = { git = "https://github.com/mesalock-linux/env_logger-sgx" }

# for wasm code
wasmi           = { git = "https://github.com/mesalock-linux/wasmi-sgx" }
serde           = { git = "https://github.com/mesalock-linux/serde-sgx" }
serde_json      = { git = "https://github.com/mesalock-linux/serde-json-sgx"}
sgxwasm         = { path = "sgxwasm" }
lazy_static     = { version = "1.1.0", features = ["spin_no_std"] }

# for attestation
chrono          = { git = "https://github.com/mesalock-linux/chrono-sgx" }
webpki          = { git = "https://github.com/mesalock-linux/webpki", branch = "mesalock_sgx", default-features = false, features = ["mesalock_sgx"] }
base64          = { git = "https://github.com/mesalock-linux/rust-base64-sgx" }
num-bigint      = { git = "https://github.com/mesalock-linux/num-bigint-sgx" }
webpki-roots    = { git = "https://github.com/mesalock-linux/webpki-roots.git", branch = "mesalock_sgx" }
serde_derive    = { git = "https://github.com/mesalock-linux/serde-sgx" }
httparse        = { version = "1.3.2", default-features = false }
itertools       = { version = "0.7.8", default-features = false, features = []}
bit-vec         = { version = "0.6", default-features = false }
untrusted       = { git = "https://github.com/briansmith/untrusted", tag = "ring-master" }

# use renamed blake2-rfc
[dependencies.blake2-no-std]
git     = "https://github.com/cesarb/blake2-rfc"
package = "blake2-rfc"
version = "0.2.18"
default-features = false

[dependencies.yasna]
git      = "https://github.com/mesalock-linux/yasna.rs-sgx"
rev      = "d4619dfa4a5ff73b8bf6e8c3bd4e977fc1634a19" # fixing to this revision to have buf public
features = ["bit-vec", "num-bigint", "chrono"]

[dependencies.rustls]
git      = "https://github.com/mesalock-linux/rustls"
branch   = "mesalock_sgx"
features = ["dangerous_configuration"]

[dependencies.my_node_runtime]
git = "https://github.com/scs/substraTEE-node"
package = "substratee-node-runtime"
default-features = false
features = ["no_global_allocator", "no_panic_handler", "no_oom"]

[dependencies.sgx_serialize_derive]
git = "https://github.com/baidu/rust-sgx-sdk"
rev = "v1.0.8"

[dependencies.primitives]
git = 'https://github.com/paritytech/substrate'
rev = "56b0273fd48b4e742e9da7317bc8e132a740b684"
package = "substrate-primitives"
default-features = false

[dependencies.runtime_primitives]
git = 'https://github.com/paritytech/substrate'
rev = "56b0273fd48b4e742e9da7317bc8e132a740b684"
package = "sr-primitives"
default-features = false

[patch.crates-io]
ring = { git = "https://github.com/mesalock-linux/ring-sgx" }

[patch.'https://github.com/paritytech/substrate']
sr-io = { git = "https://github.com/scs/substraTEE-node" }
