[package]
name = "substratee_worker_enclave"
version = "4.0.0"
authors = ["Supercomputing Systems AG <info@scs.ch>"]

[workspace]
members = [
]

[lib]
name = "substratee_worker_enclave"
crate-type = ["staticlib"]

[features]
default = []

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_tse       = { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_tstd      = { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk", features = ["untrusted_fs","net","backtrace"] }
sgx_rand      = { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_trts      = { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_types     = { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_tseal     = { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_tcrypto   = { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_serialize = { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_tunittest = { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk" }

[dependencies]
aes               = { version = "0.3.2" }
ofb               = { version = "0.1.1" }
codec             = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
primitive-types   = { version = "0.5.0", default-features = false, features = ["codec"] }
sgx-crypto-helper = { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk", package = "sgx_tcrypto_helper" }
log               = { version = "0.4.7", git = "https://github.com/mesalock-linux/log-sgx" }
env_logger        = { version = "0.6.2", git = "https://github.com/mesalock-linux/env_logger-sgx" }
serde        	= { version = "1.0.97", git = "https://github.com/mesalock-linux/serde-sgx" }
serde_json      = { version = "1.0.36", git = "https://github.com/mesalock-linux/serde-json-sgx"}
lazy_static     = { version = "1.1.0", features = ["spin_no_std"] }

# for attestation
chrono          = { version = "0.4.7",  git = "https://github.com/mesalock-linux/chrono-sgx" }
base64          = { version = "0.10.1", git = "https://github.com/mesalock-linux/rust-base64-sgx" }
num-bigint      = { version = "0.2.2",  git = "https://github.com/mesalock-linux/num-bigint-sgx" }
serde_derive    = { version = "1.0.97", git = "https://github.com/mesalock-linux/serde-sgx" }
httparse        = { version = "1.3.2",  default-features = false }
itertools       = { version = "0.7.8",  default-features = false, features = []}
bit-vec         = { version = "0.6",    default-features = false }
rust-base58     = { rev = "3fe87eafe81d1ff5e6cf2fb63c6976fc4e06ac44", git = "https://github.com/mesalock-linux/rust-base58-sgx", default-features = false, features=["mesalock_sgx"] }

[dependencies.webpki]
git              = "https://github.com/mesalock-linux/webpki"
branch           = "mesalock_sgx"
version          = "0.21.0"

[dependencies.webpki-roots]
git              = "https://github.com/mesalock-linux/webpki-roots"
branch           = "mesalock_sgx"
version          = "0.17.0"

[dependencies.yasna]
git      = "https://github.com/mesalock-linux/yasna.rs-sgx"
rev      = "29f0707027ce3b06ddb7daf4086ef673dbcb14ff"
default-features = false
features = ["bit-vec", "num-bigint", "chrono", "mesalock_sgx"]

[dependencies.rustls]
git      = "https://github.com/mesalock-linux/rustls"
rev      = "fe19b470f6acbb4c6c39fe1f83556bc434840fd8"
features = ["dangerous_configuration"]

[dependencies.sr-io]
git = "https://github.com/scs/substraTEE-node"
package = 'sr-io'
rev = 'acd97f49be1f691c35f567dd79f7391ce9554a9f'
default-features = false
features = ["no_oom", "no_panic_handler", "sgx", "debug"]

[dependencies.sgx_serialize_derive]
git = "https://github.com/baidu/rust-sgx-sdk"
rev = "v1.0.9"

[dependencies.primitives]
git = 'https://github.com/scs/substrate'
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"
package = "substrate-primitives"
default-features = false

[dependencies.runtime_primitives]
git = 'https://github.com/scs/substrate'
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"
package = "sr-primitives"
default-features = false

[dependencies.rstd]
git = 'https://github.com/scs/substrate'
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"
package = "sr-std"
features = ["no_global_allocator"]
default-features = false

[dependencies.substrate-api-client]
git = "https://github.com/scs/substrate-api-client"
rev = 'a1e82a08418dc5de0b6bd3bf016bcee004736441'
default-features = false

[dependencies.substratee-stf]
path = "../stf"
default-features = false
features = ["sgx"]


# cargo bug https://github.com/rust-lang/cargo/issues/5478
# forces us to add extra characters to github url, like introducing double slashes
[patch.'https://github.com/scs/substrate']
primitives = { git = "https://github.com/scs//substrate", package = 'substrate-primitives', tag = "substraTEE-M5.1" , default-features = false }
substrate-application-crypto = { git = "https://github.com/scs//substrate", tag = "substraTEE-M5.1", default-features = false }
sr-io = { git = "https://github.com/scs/substraTEE-node", package = 'sr-io', rev = 'acd97f49be1f691c35f567dd79f7391ce9554a9f', default-features = false }
sr-std = { git = "https://github.com/scs//substrate", tag = "substraTEE-M5.1", default-features = false }


[patch.'https://github.com/scs//substrate']
sr-io = { git = "https://github.com/scs/substraTEE-node", package = 'sr-io', rev = 'acd97f49be1f691c35f567dd79f7391ce9554a9f', default-features = false }

[patch.'https://github.com/paritytech/substrate']
primitives = { git = "https://github.com/scs//substrate", package = 'substrate-primitives', tag = "substraTEE-M5.1" , default-features = false }
substrate-application-crypto = { git = "https://github.com/scs//substrate", tag = "substraTEE-M5.1" , default-features = false }
sr-io = { git = "https://github.com/scs/substraTEE-node", package = 'sr-io', rev = 'acd97f49be1f691c35f567dd79f7391ce9554a9f' , default-features = false }
sr-std = { git = "https://github.com/scs//substrate", tag = "substraTEE-M5.1", default-features = false }

[patch.'https://github.com/scs/substrate-api-client']
primitives = { git = "https://github.com/scs//substrate", package = 'substrate-primitives', tag = "substraTEE-M5.1" , default-features = false }
sr-io = { git = "https://github.com/scs/substraTEE-node", package = 'sr-io', rev = 'acd97f49be1f691c35f567dd79f7391ce9554a9f', default-features = false }
sr-std = { git = "https://github.com/scs//substrate", tag = "substraTEE-M5.1", default-features = false }

[patch.crates-io]
ed25519-dalek = { git = "https://github.com/scs/ed25519-dalek.git", branch = "no_std_sgx"}
