[package]
name = "substratee_worker_enclave"
version = "4.0.0"
authors = ["Supercomputing Systems AG <info@scs.ch>"]

[workspace]
members = [
]

[lib]
name = "substratee_worker_enclave"
crate-type = ["staticlib"]

[features]
default = []

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_tse       = { rev = "v1.1.0", git = "https://github.com/baidu/rust-sgx-sdk.git" }
sgx_tstd      = { rev = "v1.1.0", git = "https://github.com/baidu/rust-sgx-sdk.git", features = ["untrusted_fs","net","backtrace"] }
sgx_rand      = { rev = "v1.1.0", git = "https://github.com/baidu/rust-sgx-sdk.git" }
sgx_trts      = { rev = "v1.1.0", git = "https://github.com/baidu/rust-sgx-sdk.git" }
sgx_types     = { rev = "v1.1.0", git = "https://github.com/baidu/rust-sgx-sdk.git" }
sgx_tseal     = { rev = "v1.1.0", git = "https://github.com/baidu/rust-sgx-sdk.git" }
sgx_tcrypto   = { rev = "v1.1.0", git = "https://github.com/baidu/rust-sgx-sdk.git" }
sgx_serialize = { rev = "v1.1.0", git = "https://github.com/baidu/rust-sgx-sdk.git" }
sgx_tunittest = { rev = "v1.1.0", git = "https://github.com/baidu/rust-sgx-sdk.git" }

[dependencies]
aes               = { version = "0.3.2" }
ofb               = { version = "0.1.1" }
codec             = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
primitive-types   = { version = "0.6", default-features = false, features = ["codec"] }
sgx-crypto-helper = { rev = "v1.1.0", git = "https://github.com/baidu/rust-sgx-sdk.git", package = "sgx_tcrypto_helper" }
log               = { version = "0.4", git = "https://github.com/mesalock-linux/log-sgx" }
env_logger        = { version = "0.7", git = "https://github.com/mesalock-linux/env_logger-sgx" }
serde        	= { version = "1.0.97", git = "https://github.com/mesalock-linux/serde-sgx" }
serde_json      = { version = "1.0.36", git = "https://github.com/mesalock-linux/serde-json-sgx"}
lazy_static     = { version = "1.1.0", features = ["spin_no_std"] }

# for attestation
chrono          = { version = "0.4.7",  git = "https://github.com/mesalock-linux/chrono-sgx" }
base64          = { version = "0.10", git = "https://github.com/mesalock-linux/rust-base64-sgx" }
num-bigint      = { version = "0.2",  git = "https://github.com/mesalock-linux/num-bigint-sgx" }
serde_derive    = { version = "1.0", git = "https://github.com/mesalock-linux/serde-sgx" }
httparse        = { version = "1.3",  default-features = false }
itertools       = { version = "0.8",  default-features = false, features = []}
bit-vec         = { version = "0.6",    default-features = false }
rust-base58     = { rev = "3fe87eafe81d1ff5e6cf2fb63c6976fc4e06ac44", git = "https://github.com/mesalock-linux/rust-base58-sgx", default-features = false, features=["mesalock_sgx"] }

[dependencies.webpki]
git              = "https://github.com/mesalock-linux/webpki"
branch           = "mesalock_sgx"
version          = "0.21.0"

[dependencies.webpki-roots]
git              = "https://github.com/mesalock-linux/webpki-roots"
branch           = "mesalock_sgx"
version          = "0.17.0"

[dependencies.yasna]
git      = "https://github.com/mesalock-linux/yasna.rs-sgx"
rev      = "29f0707027ce3b06ddb7daf4086ef673dbcb14ff"
default-features = false
features = ["bit-vec", "num-bigint", "chrono", "mesalock_sgx"]

[dependencies.rustls]
git      = "https://github.com/mesalock-linux/rustls"
rev      = "fe19b470f6acbb4c6c39fe1f83556bc434840fd8"
features = ["dangerous_configuration"]

[dependencies.sr-io]
default-features = false
optional = true
git = "https://github.com/scs/substraTEE-node"
branch = "cl-introduce_host_calls_via_runtime_interface"
#rev = "acd97f49be1f691c35f567dd79f7391ce9554a9f"
package = "sr-io"
features = ["disable_oom", "disable_panic_handler", "disable_allocator", "sgx"]

[dependencies.sgx_serialize_derive]
git = "https://github.com/baidu/rust-sgx-sdk.git"
rev = "v1.1.0"

[dependencies.primitives]
git = "https://github.com/paritytech/substrate"
rev = "3bf9540e72df5ecb3955845764dfee7dcdbb26b5"
package = "substrate-primitives"
default-features = false
features = ["full_crypto"]

[dependencies.application-crypto]
git = "https://github.com/paritytech/substrate"
rev = "3bf9540e72df5ecb3955845764dfee7dcdbb26b5"
package = "substrate-application-crypto"
default-features = false
features = ["full_crypto"]

[dependencies.runtime_primitives]
git = "https://github.com/paritytech/substrate"
rev = "3bf9540e72df5ecb3955845764dfee7dcdbb26b5"
package = "sr-primitives"
default-features = false

[dependencies.rstd]
git = "https://github.com/paritytech/substrate"
rev = "3bf9540e72df5ecb3955845764dfee7dcdbb26b5"
package = "sr-std"
default-features = false

[dependencies.substrate-api-client]
git = "https://github.com/scs/substrate-api-client"
branch = "cl-update-to-3bf9540e72df5ecb3955845764dfee7dcdbb26b5"
#rev = "a1e82a08418dc5de0b6bd3bf016bcee004736441"
default-features = false
features = ["full_crypto"]

[dependencies.substratee-stf]
path = "../stf"
default-features = false
features = ["sgx"]


[patch."https://github.com/paritytech/substrate"]
sr-io = { git = "https://github.com/scs/substraTEE-node", branch = "cl-introduce_host_calls_via_runtime_interface", default-features = false, features = ["disable_oom", "disable_panic_handler", "disable_allocator", "sgx"]}

# environment logger still depends on v1.0.9
[patch."https://github.com/baidu/rust-sgx-sdk.git"]
sgx_tstd = { git = "https://github.com/apache/incubator-mesatee-sgx/", rev = "v1.1.0" }
