[package]
name = "substratee_worker_enclave"
version = "1.0.0"
authors = ["Supercomputing Systems AG <info@scs.ch>"]

[lib]
name = "sealedkeyenclave"
crate-type = ["staticlib"]

[features]
default = []

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_tstd = { git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_rand = { git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_types = { git = "https://github.com/baidu/rust-sgx-sdk"}
sgx_tseal = { git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_tcrypto = { git = "https://github.com/baidu/rust-sgx-sdk" }
rust-crypto = { git = "https://github.com/baidu/rust-sgx-sdk" }
rust-base58 = { git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_serialize = { git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_crypto_helper = { package="sgx_tcrypto_helper", git = "https://github.com/baidu/rust-sgx-sdk" }

[target.'cfg(target_env = "sgx")'.dependencies]
sgx_crypto_helper = { package="sgx_tcrypto_helper", git = "https://github.com/baidu/rust-sgx-sdk" }

[dependencies]
blake2-rfc = { version = "0.2.18", default-features = false}
parity-codec = { version = "3.0", default-features = false }
primitive-types = { version = "0.2", default-features = false, features = ["codec"] }

[dependencies.my_node_runtime]
git = "https://github.com/scs/substraTEE-node"
tag = "M1"
package = "substratee-node-runtime"
default-features = false
features = ["no_global_allocator"]

[dependencies.serde_json]
git = "https://github.com/baidu/rust-sgx-sdk"

[dependencies.sgx_serialize_derive]
git = "https://github.com/baidu/rust-sgx-sdk"

# !!!!!! no_std trouble https://github.com/w3f/schnorrkel/issues/31
# [dependencies.schnorrkel]
# git = "https://github.com/scs/schnorrkel"
# default-features = false
# features=["alloc", "u64_backend"]

[dependencies.primitives]
git = 'https://github.com/paritytech/substrate'
rev = '6e67eff0653677d3d01980ca822c4b8a227914a3'
package = "substrate-primitives"
default-features = false

#only listed to get no_global_allocator feature in
[dependencies.rstd]
git = 'https://github.com/paritytech/substrate'
rev = '6e67eff0653677d3d01980ca822c4b8a227914a3'
package = "sr-std"
default-features = false
features = ["no_global_allocator"]

#only listed to get no_panic_handler and no_oom features in
[dependencies.runtime_io]
git = 'https://github.com/paritytech/substrate'
rev = '6e67eff0653677d3d01980ca822c4b8a227914a3'
package = "sr-io"
default-features = false
features = ["no_panic_handler", "no_oom"]

[dependencies.runtime_primitives]
git = 'https://github.com/paritytech/substrate'
rev = '6e67eff0653677d3d01980ca822c4b8a227914a3'
package = "sr-primitives"
default-features = false

