[package]
name = "substratee_worker"
version = "4.0.0"
authors = ["Supercomputing Systems AG <info@scs.ch>"]
build = "build.rs"

[dependencies]
ws 						= "0.7"
hex 					= "0.3"
log 					= "0.4"
env_logger 				= "0.6"
rust-base58 			= "0.0.4"
rust-crypto 			= "0.2"
clap 					= { version = "2.33", features = [ "yaml" ] }

dirs 					= "1.0.2"
serde 					= "1.0"
serde_json 				= "1.0"
serde_derive 			= "1.0"

# ipfs
ipfs-api				= "0.5.0-alpha2"
futures 				= "0.1"
hyper 					= "0.12"
multihash 				= "0.8"
cid 					= "0.3"
sha2 					= { version = "0.7", default-features = false }

codec           		= { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
primitive-types    		= { version = "0.5.0", default-features = false, features = ["codec"] }

sgx_urts				= { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_types 				= { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_tseal				= { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_ucrypto 			= { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_crypto_helper 		= { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk", default-features = false}

[dependencies.substrate-api-client]
git = "https://github.com/scs/substrate-api-client"
rev = 'a1e82a08418dc5de0b6bd3bf016bcee004736441'

[dependencies.substratee-node-calls]
path = "../substratee-node-calls"

[dependencies.substratee_worker_api]
path = "worker-api"

[dependencies.my_node_runtime]
git = "https://github.com/scs/substraTEE-node"
rev = "acd97f49be1f691c35f567dd79f7391ce9554a9f"
package = "substratee-node-runtime"
default-features = false
features = ["no_global_allocator"]

[dependencies.runtime_primitives]
git = 'https://github.com/scs/substrate'
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"
package = "sr-primitives"

[dependencies.balances]
git = "https://github.com/scs/substrate"
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"
package = "srml-balances"

[dependencies.node-primitives]
git = "https://github.com/scs/substrate"
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"

[dependencies.primitives]
git = "https://github.com/scs/substrate"
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"
package = "substrate-primitives"

[dependencies.substrate-keyring]
git = "https://github.com/scs/substrate"
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"

[dependencies.system]
git = "https://github.com/scs/substrate"
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"
package = "srml-system"

[dependencies.substratee-stf]
path = "../stf"
default-features = false

[features]
default = ["std"]
std = [
	"primitives/std",
	"codec/std",
	"my_node_runtime/std",
]

