[package]
name = "substratee_worker"
version = "4.0.0"
authors = ["Supercomputing Systems AG <info@scs.ch>"]
build = "build.rs"

[dependencies]
ws 						= "0.7"
hex 					= "0.3"
log 					= "0.4"
env_logger 				= "0.6"
rust-base58 			= "0.0.4"
rust-crypto 			= "0.2"
clap 					= { version = "2.33", features = [ "yaml" ] }

# for wasm
wabt 					= "0.4.0"
dirs 					= "1.0.2"
wasmi 					= "0.4.5"
serde 					= "1.0"
serde_json 				= "1.0"
serde_derive 			= "1.0"
nan-preserving-float 	= "0.1.0"

# ipfs
ipfs-api				= "0.5.0-alpha2"
futures 				= "0.1"
hyper 					= "0.12"
multihash 				= "0.8"
cid 					= "0.3"
sha2 					= { version = "0.7", default-features = false }

parity-codec 			= { version = "3.0", default-features = false }
primitive-types 		= { version = "0.2", default-features = false, features = ["codec"] }

sgx_urts				= { rev = "v1.0.8", git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_types 				= { rev = "v1.0.8", git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_tseal				= { rev = "v1.0.8", git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_ucrypto 			= { rev = "v1.0.8", git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_crypto_helper 		= { rev = "v1.0.8", git = "https://github.com/baidu/rust-sgx-sdk", default-features = false}

[dependencies.substrate-api-client]
git = "https://github.com/scs/substrate-api-client"
rev = "61bc5233582952a9ff13ab24fb93b08396758bf1"

[dependencies.substratee-node-calls]
path = "../substratee-node-calls"

[dependencies.substratee_worker_api]
path = "worker-api"

[dependencies.my_node_runtime]
git = "https://github.com/scs/substraTEE-node"
tag = "M4"
package = "substratee-node-runtime"
default-features = false
features = ["no_global_allocator"]

[dependencies.balances]
git = "https://github.com/paritytech/substrate"
rev = "56b0273fd48b4e742e9da7317bc8e132a740b684"
package = "srml-balances"

[dependencies.node-primitives]
git = "https://github.com/paritytech/substrate"
rev = "56b0273fd48b4e742e9da7317bc8e132a740b684"

[dependencies.primitives]
git = "https://github.com/paritytech/substrate"
rev = "56b0273fd48b4e742e9da7317bc8e132a740b684"
package = "substrate-primitives"

[dependencies.substrate-keyring]
git = "https://github.com/paritytech/substrate"
rev = "56b0273fd48b4e742e9da7317bc8e132a740b684"

[dependencies.system]
git = "https://github.com/paritytech/substrate"
rev = "56b0273fd48b4e742e9da7317bc8e132a740b684"
package = "srml-system"

[features]
default = ["std"]
std = [
	"primitives/std",
	"parity-codec/std",
	"my_node_runtime/std",
]

