[package]
name = "wasm-runtime"
version = "0.1.0"
authors = ["Marcel Frei <marcel.frei@electronix.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type =["cdylib"]

[dependencies]
