[package]
name = "sgx-runtime"
version = "0.1.0"
authors = ["Supercomputing Systems AG <info@scs.ch>"]
edition = "2018"

[dependencies]

[dependencies.application-crypto]
default-features = false
git = "https://github.com/paritytech/substrate"
rev = "3bf9540e72df5ecb3955845764dfee7dcdbb26b5"
package = "substrate-application-crypto"
features = ["full_crypto"]

[dependencies.balances]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "pallet-balances"
rev = "3bf9540e72df5ecb3955845764dfee7dcdbb26b5"

[dependencies.indices]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "pallet-indices"
rev = "3bf9540e72df5ecb3955845764dfee7dcdbb26b5"

[dependencies.codec]
default-features = false
package = "parity-scale-codec"
version = "1.0.0"
features = ["derive"]

[dependencies.primitives]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "substrate-primitives"
rev = "3bf9540e72df5ecb3955845764dfee7dcdbb26b5"
features = ["full_crypto"]

[dependencies.runtime_primitives]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "sr-primitives"
rev = "3bf9540e72df5ecb3955845764dfee7dcdbb26b5"

[dependencies.support]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "palette-support"
rev = "3bf9540e72df5ecb3955845764dfee7dcdbb26b5"

[dependencies.system]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "palette-system"
rev = "3bf9540e72df5ecb3955845764dfee7dcdbb26b5"

[dependencies.version]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "sr-version"
rev = "3bf9540e72df5ecb3955845764dfee7dcdbb26b5"


